version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=klkmanin
      - POSTGRES_DB=ebayCopyDB