version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
      MYSQL_DATABASE: mynotes
    ports:
      - "3306:3306"
