version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
      MYSQL_DATABASE: movieswatched
    ports:
      - "3306:3306"
